### ISSUE TITLE
missing space characters after editing

### ISSUE THREAD

**Issue by pirolen** [cisocrgroup/pocoweb#44] opened 2020-12-15 16:01 UTC
Hi, we started testing your tool. We imported Abbyy-xml files and .png images and make some character corrections. After saving the XML, all space characters disappear.
See screenshot for a minimal example of the aligned original xml and the newly saved xml, with a transformed `charParams `element, e.g. 
`<charParams l="1561" t="532" r="1591" b="597" />`

I also attach the original png and xml. Thanks.

(removed attachments now)

**Comment by finkf** [comment] 2020-12-16 09:46
Thanks for reporting this.  It seems as if the xml formatter does not preserve the whitespace within the charParam tags.  I will look into this issue.

**Comment by pirolen** [comment] 2020-12-16 09:56
Thanks very much. Quick question: in which format are the images accepted, .png only?

**Comment by finkf** [comment] 2020-12-16 10:12
No.  .jpg and .tif should be supported as well.

**Comment by pirolen** [comment] 2021-01-11 18:15
> Thanks for reporting this. It seems as if the xml formatter does not preserve the whitespace within the charParam tags. I will look into this issue.

We would be happy to test it on more of our data.

**Comment by finkf** [comment] 2021-01-12 09:40
I am going to publish a fix for this in the next few days.

**Comment by finkf** [comment] 2021-01-13 15:53
I just uploaded a fix for your problems to #39

**Comment by pirolen** [comment] 2021-01-15 11:23
Thanks, will check! Regarding manual corrections of font style: we used Abbyy for the OCR, and were able to correct for e.g. superscript, when the superscript styling was there, but its segment boundary was missing. Is it also possible to manually add the styling in those cases, when a character is e.g. bold typeface, but is not recognized as such?

**Comment by jpb-badw** [comment] 2021-01-18 11:25
> I just uploaded a fix for your problems to #39

I've run `git checkout releases/v0.9.17 ` to update the release after this issue, however it seems that its up to date (without the fix).
Could it be due to [**this error?**](https://github.com/cisocrgroup/pocoweb/runs/1696109176)

**Comment by finkf** [comment] 2021-01-18 11:40
have you run `git fetch` before checking out releases/v0.9.17?

**Comment by jpb-badw** [comment] 2021-01-18 12:28
> have you run `git fetch` before checking out releases/v0.9.17?

I've successfully updated it after running `git fetch` too and now the issue is solved. 
Thank you

**Comment by jpb-badw** [comment] 2021-02-16 12:28
Hello,
we have encountered an issue regarding the spaces.
We imported Abbyy-XMLfiles and .png images, corrected some lines and exported it. In this case, the charParams line doesn’t disappear completely but doesn’t seem to show the space that should be there. e.g. 

`
<charParams l="989" t="1326" r="997" b="1351"></charParams>`


Here is the space visible in the PoCoWeb editor.
![ErrorMWText](https://user-images.githubusercontent.com/73533526/108061836-2af48400-7059-11eb-87ea-c2778ffeb43b.png)

ABBY-XML with space:
```
<charParams l="962" t="1330" r="971" b="1351">t</charParams>
<charParams l="974" t="1333" r="988" b="1351">e</charParams>
<charParams l="989" t="1326" r="997" b="1351"> </charParams>
<charParams l="998" t="1326" r="1020" b="1350">Z</charParams>
<charParams l="1023" t="1334" r="1037" b="1351">a</charParams>
```
Exported XML Line 

```
 <charParams l="962" t="1330" r="971" b="1351">t</charParams>
       <charParams l="974" t="1333" r="988" b="1351">e</charParams>
       <charParams l="989" t="1326" r="997" b="1351"></charParams>
       <charParams l="998" t="1326" r="1020" b="1350">Z</charParams>
       <charParams l="1023" t="1334" r="1037" b="1351">a</charParams>
```
_Attaching XML files is not supported_

**Closed** 2021-07-06 09:06 UTC
